name: build
on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Ren'Py
        uses: remarkablegames/setup-renpy@v2
        with:
          web: true

      - name: Delete unnecessary files
        run: >
          find .
          ! -name "icon.*"
          ! -name "progressive_download.txt"
          ! -name "web-*"
          ! -path "*/.*"
          ! -path "*game*"
          -delete

      - name: Build web
        run: renpy-launcher web_build . --destination web

      - name: Update presplash image
        run: |
          rm web/web-presplash.jpg
          mv web-presplash.webp web
          grep -lr web-presplash.jpg web | xargs sed -i 's/web-presplash.jpg/web-presplash.webp/g'

      - name: Deploy site
        if: github.ref_name == 'master'
        uses: remarkablemark/gitploy-action@v1
        with:
          directory: web

      - name: Upload artifacts
        if: github.ref_name == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: web
