name: lint
on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Ren'Py
        uses: remarkablegames/setup-renpy@v2

      - name: Lint script
        run: |
          renpy-cli game lint
          if (( $(renpy-cli game lint | wc -l) > 13 )); then
            exit 1
          fi
