name: release-please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release

  deploy:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release_created }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ren'Py
        uses: remarkablegames/setup-renpy@v1
        id: renpy
        with:
          web: true

      - name: Web build
        run: renpy-cli ${{ steps.renpy.outputs.launcher }} web_build . --destination web

      - name: Setup butler
        uses: remarkablegames/setup-butler@v1

      - name: Upload to itch.io
        run: butler push web ${{ github.repository }}:web --userversion-file version.txt
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      - name: Upload Release Artifact
        run: gh release upload ${{ needs.release.outputs.tag_name }} web.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
